/** Minimal SaveData-shaped blob for new cloud slots (mirrors client defaultSave). */
export function defaultSaveJson(): Record<string, unknown> {
  return {
    version: 5,
    roomId: 'overworld',
    hp: 6,
    maxHp: 6,
    hasSword: false,
    hasKey: false,
    bossDefeated: false,
    flags: {},
    killed: [],
    collected: [],
    xp: 0,
    level: 1,
    coins: 0,
    stacks: {},
    bag: [],
    nextItemUid: 1,
    equipped: {
      weapon: null,
      shield: null,
      helmet: null,
      breastplate: null,
      greaves: null,
      shoes: null,
      gloves: null,
      amulet: null,
      ring: null,
      key: null,
    },
    attrs: { str: 1, dex: 1, vit: 1, int: 1, lck: 1 },
    attrPoints: 0,
    armor: 0,
    discoveredMapz: ['surface'],
    visitedRooms: [],
    princessSaved: false,
    landsCleared: [],
    runSeed: (Math.floor(Math.random() * 0xffffffff) >>> 0) || 1,
    bestBudId: null,
    bestBudStage: 'none',
  };
}
